; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:rymcu-esp32-s3-devkitc-1]
platform = espressif32
board = rymcu-esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
 
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_CONF_SUPPRESS_DEFINE_CHECK
    -I include
 
lib_deps =
    lovyan03/LovyanGFX@^1.1.16
    lvgl/lvgl@^9.2.2
    mathertel/RotaryEncoder@^1.6.0


#gfx.setRotation(0); // тот же разворот, что подобрали ранее (вверх ногами иначе)
#Поворот выставил на 0 т.к. на этой библиотеки он не развёрнуть "вверх ногами"
#cfg.offset_y = 20;         // если изображение смещено - подправим тут 
#Специально выставил смещение на 20 едини. Теперь всё идеально влезает на экран. раньше была чёрная полоса
